
version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - sudo yum install -y docker
      - sudo nohup /usr/bin/dockerd &
  build:
    commands:
      - echo Building Docker images...
      - docker build -t my-image .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push my-repository-url

artifacts:
  files:
    - '**/*'
