version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing Docker...
      - sudo yum install -y docker
      - echo Starting Docker...
      - sudo nohup /usr/bin/dockerd &
      - sleep 20 # Wait for Docker to fully initialize
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      # Your build steps here...
  post_build:
    commands:
      - echo Build completed on `date`
      # Your post-build steps here...


artifacts:
  files:
    - '**/*'
